Fix: Corregir ruta de logger en emailAlert.service.js
Problema:
- Error: Cannot find module '../utils/logger'
- En Store el logger está en config/ no en utils/

Solución:
- Cambiado require('../utils/logger') a require('../config/logger')
- Línea 3 de emailAlert.service.js

El Store ahora inicia correctamente.